# Header
menu:
  Home: /
  About: /about
  Journey: /categories/Journey/
  Lifestyle: /categories/Lifestyle/
  RV Highlight: /categories/RV-Highlight/
  RV Info: /categories/RV-Info/

rss: /atom.xml

# User Info
user_name: RV Galleries
user_avatar: https://www.rvgalleries.com/content/images/rvlogo.png
user_location: Earth
user_description: "Are you a new RV owner, or perhaps want to become one? This site will explain the dissimilarities between the various kinds of RVs and towable trailers so that you can get the one that is right for you! Also you can find out more about RVs by going through to our site."
user_contact: 
user_introduction: 
github_username: 
twitter_username: 
weibo_username:
zhihu_username: 
facebook_username:
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: true
livere_uid: MTAyMC8yOTE4Ni81NzUz

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


